services:
  ## Minio config
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY_FILE: access_key
      MINIO_SECRET_KEY_FILE: secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
volumes:
  minio_storage: